version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    ports:
      - "80:8000" # Memetakan Port 80 VPS ke Port 8000 di dalam Container
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=production
    depends_on:
      - db
    networks:
      - project-network

  # Database MySQL
  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: kuis
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - project-network

networks:
  project-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local